# Quarkus
quarkus.http.port=8080

# Kafka (Dev Services starts a broker automatically with Podman/Docker)
camel.component.kafka.brokers=${kafka.bootstrap.servers:localhost:9092}

# Loyalty API (mock endpoint running inside this app)
loyalty.api.url=localhost:${quarkus.http.port}

# File ingestion
# file.orders.incoming=orders/incoming

# Logging
quarkus.log.category."org.apache.camel".level=INFO
quarkus.log.category."org.apache.kafka".level=WARN

# Test overrides
%test.file.orders.incoming=target/test-orders/incoming
%test.quarkus.test.integration-test-profile=test
%test.quarkus.devservices.enabled=false
%test.camel.component.kafka.additional-properties[max.block.ms]=500
%test.camel.component.kafka.additional-properties[request.timeout.ms]=500
%test.camel.component.kafka.additional-properties[delivery.timeout.ms]=1000
%test.camel.component.kafka.additional-properties[linger.ms]=0
%test.camel.component.kafka.additional-properties[retries]=1
%test.camel.component.kafka.additional-properties[enable.idempotence]=false
